workflows:
  android-workflow:
    name: Android Build Workflow
    environment:
      groups: []
      flutter: "3.4.0"  # استخدام إصدار محدد لحل مشكلة البناء
      xcode: "15.0"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
