workflows:
  android-workflow:
    name: Android Build Workflow
    environment:
      groups: []
      flutter: "stable"  # استخدام أحدث إصدار مستقر تلقائياً
    scripts:
      - name: Build APK
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
